config/routes.rb
Rails.application.routes.draw do
  get 'project_states/update'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'projects#index'

  resources :projects do
    resource :github_webhooks, only: :create, defaults: { formats: :json }
    resources :topics, only: [:create, :show, :update] do
      resources :comments, shallow: true, only: [:create, :update]
    end
    resources :project_states, only: :update
    resources :orders, only: [:create, :update]
    member do
      get 'file/:sha', to: 'repositories#show'
    end
  end

  resources :order_lines, only: :destroy
  resources :meetings

  require "sidekiq/web"
  mount Sidekiq::Web => '/sidekiq'


  mount Attachinary::Engine => "/attachinary"
  mount ActionCable.server => '/cable'

end

app/models/topic.rb
class Topic < ApplicationRecord
  # TO DO => drop category table?
  belongs_to :user
  belongs_to :project

  has_many :comments, dependent: :destroy

  validates :state, :user, :project, presence: true
  validates :type, presence: true, inclusion: { in: %w(PullRequest Issue) }
  validates :github_number, presence: true, uniqueness: { scope: :id,
    message: "Topic number already exists" }, on: :update

  attr_accessor :content, :title
end

app/models/topic/issue.rb
class Issue < Topic

  def self.model_name
     Topic.model_name
   end
end

app/models/topic/pull_request.rb
class PullRequest < Topic

  def self.model_name
     Topic.model_name
   end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :find_project, only: [:show, :create, :edit, :update, :destroy]
  before_action :topic_update_params, only: :update

  def show
    @state_machine = @project.state_machine
    @repo_tree = RepoManager.new(current_user.id, @project.id).retrieve_repo_architecture("master")
    @topic = Topic.includes(:comments).find(params[:id]) # not sure to need include
    authorize @topic
    @topic_hash = TopicManager.new(current_user.id, @project.id).get_topic_hash(@topic.github_number)
    @comments = @topic.comments
    # @topic_comments = TopicManager.new(current_user.id, @project.id).get_topic_and_comments(@topic.github_number)
  end

  def create
    @topic = @project.topics.build(topic_params)
    authorize @topic
    @topic.type ||= 'PullRequest'
    @topic.state = 'open'
    @topic.user = current_user
    @topic.project_state = @project.state_machine.current_state.to_sym
    title = params[:topic][:title]
    content = params[:topic][:content]
    if @topic.type == 'PullRequest'
      #  TO DO ?
    else
      @gh_topic = TopicManager.new(current_user.id, @project.id).create_issue(title, content)
    end
    @topic.github_number = @gh_topic[:number]
    @topic.save
    @gh_topic[:topic] = @topic
  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    if params[:topic_action] == 'merged'
      github_response = TopicManager.new(current_user.id, @project.id).merge_topic_pr(@topic.github_number)
    elsif params[:topic_action] == 'closed' && @topic.state != 'closed'
      github_response = TopicManager.new(current_user.id, @project.id).close_issue(@topic.github_number)
    elsif params[:topic_action] == 'open' && @topic.state != 'open'
      github_response = TopicManager.new(current_user.id, @project.id).reopen_issue(@topic.github_number)
    end
    edit_state(github_response)
    @topic.save
    redirect_to project_topic_path(@project, @topic)
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end

  def topic_params
    params.require(:topic).permit(:type, :title, :content)
  end

  def topic_update_params
    params.permit(:topic_action)
  end

  def edit_state(github_response)
    if github_response[:merged] && @topic.type == 'PullRequest'
      @topic.state = 'closed'
    elsif github_response[:state] != @topic.state && @topic.type == 'Issue'
      @topic.state = github_response[:state]
    elsif github_response[:merged].nil? && @topic.type == 'PullRequest'
      @topic.errors << 'Something went wrong. Contact support.'
    end
  end
end

app/helpers/topics_helper.rb
# TO DO  => review UX
module TopicsHelper
  def topic_button_color(state)
    if state == 'closed'
      return ['green', "check_circle"]
    else
      return ['orange', 'pause_circle_filled']
    end
  end

  def state_button_tag(state, options={})
    icon_attr = topic_button_color(state)
    color = icon_attr.first
    picto = icon_attr.last
    content_tag(:i, picto, class: "material-icons #{color} #{options[:class]}")
  end
end

app/views/topics/_comments.html.erb
<div class="main">
  <ul class="collapsible custom-accordion" data-collapsible="accordion" id='comment-form-accordion'>
    <li>
    <!-- collapsible-header => class -->
      <ul class='list-inline'>
        <li class= 'main-item'>
          <h4 class='part-title'>Topic: <%= @topic_hash[:title]%>
          </h4>
        </li>
        <li>
          <a class="btn-icon">
            <%= state_button_tag(@topic_hash[:state], {class:'small'}) %>
          </a>
        </li>
        <!-- <li>
          <a class="btn-icon-large"><i class="material-icons turquoise">add_circle_outline</i></a>
        </li> -->
      </ul>
      <div class="collapsible-body" id='comment-form'>
        <p>TO DO Show Details</p>
        <%#= render 'comments/new', topic: Comment.new %>
      </div>
    </li>
  </ul>


  <div id='topic-body' class="card horizontal topic z-depth-1 <%= size %>">
    <div class="card-stacked">
      <div class="card-content info-group">
        <ul class='list-inline'>
          <li><%= image_tag @topic.user.picture, alt:"writer_picture", class:"avatar-#{size}" %>
          </li>
          <li class='main-info'><%= @topic.user.github_login %></li>
          <li class='main-item fade right-align'><%= formatted_date(@topic.created_at) %></li>
        </ul>
        <p class='second-info <%= size %>'><%= simple_format @topic_hash[:body] %></p>
      </div>
    </div>
  </div>

  <div class='scroll-collection'>
    <ul class="collection" id='comments-wrapper' >
      <% @comments.each do | comment | %>
        <%= render 'comments/comment', size: size, comment: comment %>
      <% end %>
      <li class="collection-item avatar info-group form  <%= size %>">
        <%= image_tag current_user.picture, alt:"writer_picture", class:"avatar-#{size}" %>
        <div class="title">
          <span class='main-info'><%= current_user.github_login %></span>
          <span class='second-info'>
            <%= formatted_date(Date.today) %>
          </span>
          <span class='second-info'><a href="#!" class="secondary-content"><i class="material-icons">star_border</i></a></span>
        </div>
        <p class="second-info content" id='comment-form'>
          <!-- Comment.new, url: project_topic_comments_path(@project, @topic) -->
          <%= render 'comments/form', size: size %>
        </p>

      </li>
    </ul>
  </div>
</div>

app/views/topics/_filters.html.erb
<%#= simple_form_for :search_topic do |f| %>
  <%#= f.input :title, collection: %w(a b c other), label: false, multiple: true, wrapper_html: { class: 's12' } %>
<%# end %>

app/views/topics/_index.html.erb
<div id="topic-wrapper">
  <% @topic_hashes.each do | topic | %>
      <%= render 'topics/topic_card', topic_hash: topic %>
  <% end %>
</div>

app/views/topics/_issue_actions.html.erb
<ul class="list-inline space-around">
  <li>
     <% if topic.state == 'open' %>
      <%= link_to 'Close', project_topic_path(@project, topic, topic_action: 'closed'), method: :put, class: 'btn' %>
    <% elsif topic.state == 'closed' %>
      <%= link_to 'Re-open', project_topic_path(@project, topic, topic_action: 'open'), method: :put, class: 'btn' %>
    <% end %>
  </li>
  <li><%= link_to 'Delete', project_topic_path(@project, topic, delete: true), method: :put, class: 'btn gray-light' %></li>
</ul>

app/views/topics/_new.html.erb
<%= simple_form_for :topic, url: project_topics_path(@project), remote: true do |f| %>
  <%= f.error_notification %>
  <%= f.input :title, as: :string, wrapper_html: { class: 's10' } %>
  <%= f.input :content, as: :text, wrapper_html: { class: 's12' } %>
  <%= f.input :type, as: :hidden, input_html: {value: 'Issue'} %>
  <%= f.button :button, 'ok', class:'btn btn-mini', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."} %>
<% end %>

app/views/topics/_pull_request_actions.html.erb
<% if topic.state == 'open' %>
  <ul class="list-inline space-around">
     <li>
     <%= link_to 'Validate', project_topic_path(@project, topic, topic_action: 'merged'), method: :put, class: 'btn' %>
     </li>
    <li>
      <%= link_to 'Close', project_topic_path(@project, topic, topic_action: 'closed'), method: :put, class: 'btn gray-light' %>
    </li>
    <li><%= link_to 'Delete', project_topic_path(@project, topic, delete: true), method: :put, class: 'btn gray-light' %></li>
  </ul>
<% end %>

app/views/topics/_topic_card.html.erb
<% db_topic = topic_hash[:topic]%>
<div class="card horizontal topic">
  <div class="card-stacked">
    <div class="card-content info-group">
      <ul class='title-action'>
        <li><h6 class="header main-info"><%= topic_hash[:title] %></h6></li>
        <li>
          <a class="btn-icon">
            <%= state_button_tag(topic_hash[:state]) %>
          </a>
        </li>
      </ul>

      <ul class='list-inline second-info'>
        <li><%= image_tag db_topic.user.picture, class:"avatar-mini" %>
        </li>
        <li><%=db_topic.user.name %></li>
      </ul>
    </div>
    <% if db_topic.comments.any? %>
      <div class="card-action bg-white">
        <ul class='list-inline'>
          <li>Contributors:</li>
          <li>
            TO DO
          </li>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="card-link-abs">
    <%= link_to '', project_topic_path(@project.id, db_topic.id) %>
  </div>
</div>

app/views/topics/create.js.erb
<% if @topic.valid? %>
  $('#topic-form form')[0].reset();
  $('#topic-form-accordion .collapsible-header').click();
  $('#topic-wrapper').prepend("<%= j render 'topic_card', topic_hash: @gh_topic %>");
<% else %>
  $('#topic-form').fadeIn('<%= j render "new", topic: @topic%>' );
<% end %>
ajax_resize

app/views/topics/show.html.erb
<div class="col s2 full light-vt-border-right">
    <%= render 'shared/project_infos' %>
  </div>
<% if @topic.type == 'PullRequest' %>
  <!-- Project Overview -->
  <div class="col s6 full">
    <h1> 3D Preview</h1><br><br><br><br><h1>Work In Progress</h1>
    <%= render 'topics/pull_request_actions', topic: @topic %>
  </div>
  <div class="col s4 full light-vt-border-left">
    <%= render 'topics/comments', size: 'mini' %>
  </div>
<% else %>
  <div class="col s10 full">
    <%= render 'topics/comments', size: 'sm' %>
    <%= render 'topics/issue_actions', topic: @topic %>
  </div>
<% end %>