config/routes.rb
Rails.application.routes.draw do
  get 'project_states/update'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'projects#index'

  resources :projects do
    resource :github_webhooks, only: :create, defaults: { formats: :json }
    resources :topics, only: [:create, :show, :update] do
      resources :comments, shallow: true, only: [:create, :update]
    end
    resources :project_states, only: :update
    resources :orders, only: [:create, :update]
    member do
      get 'file/:sha', to: 'repositories#show'
    end
  end

  resources :order_lines, only: :destroy
  resources :meetings

  require "sidekiq/web"
  mount Sidekiq::Web => '/sidekiq'


  mount Attachinary::Engine => "/attachinary"
  mount ActionCable.server => '/cable'

end

app/views/shared/_breadcrumb.html.erb
<% if @project && @project.persisted? %>
  <div class="nav-wrapper bg-gray-lighter" id='breadcrumb'>
    <ul class="list-inline flex-start">
      <li class="project-info">
      <%= link_to project_path(@project) do %>
        <div class='project-title'><%= @project.title %></div>
        <div class='date'><%= formatted_date(@project.created_at) %></div>
      <% end %>
      </li>
      <li class="col s5">
        <% breadcrumb_items.each do |key, value | %>
          <span class="breadcrumb"><%= value.capitalize %></span>
        <% end %>
      </li>
      <li class="col s5">
        <ul class='tabs row'>
          <% @project.users.each do |user| %>
            <li class='col'>
              <%= render 'shared/user_badge', user: user %>
            </li>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_image_project_card.html.erb
<div class="card project-card">
  <div class="card-image">
    <%= link_to project_path(project), class:'title' do %>
      <% if project.picture %>
        <%= cl_image_tag project.picture.path, width: 314, crop: :fill, class:'responsive-img' %>
      <% else %>
        <%= image_tag 'missing_3d_picture.png',  style: 'width:100%;', class:'responsive-img' %>
      <% end %>
    <% end %>
  </div>
  <div class="card-content row flex">
    <div class="main-flex">
      <h6><%= link_to truncate_project(project.title), project_path(project), class:'title' %></h6>
      <!-- <p class='date'><%#= formatted_date(project.created_at) %></p> -->
    </div>
    <%= link_to "#" do %>
      <% if project_user_activities(project) > 0 %>
        <div class="badge-container">
          <i class="material-icons small">notifications</i>
          <div class="badge red"><%= project_user_activities(project) %></div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="card-action flex row">
    <div class='main-flex'>
      <span id='progress-index'></span>
      <span class='date'>Due date: <%= formatted_date(project.due_date) %></span>
    </div>

    <div class="small-size color-<%= project.state_machine.current_state %>">
      <%= project.state_machine.current_state.gsub('_', ' ').capitalize %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class='nav-<%= size %>'>
  <div id= 'logo-nav' class="nav-wrapper">
    <!-- Logo -->
    <%= link_to root_path, class: "brand-logo" do %>
      <%= image_tag "logo.png" %>
    <% end %>


    <!-- Burger button for small device -->
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">view_headline</i></a>

    <!-- Right Navigation -->
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <!-- Different navigation if login or not -->
      <% if user_signed_in? %>
        <%if user_signed_in? && @project && @project.id %>
        <li>
          <%= simple_form_for :user, url: project_project_state_path(@project), method: :put do |f| %>
            <%= f.input :category, collection: ['client', 'methods', 'production'], wrapper_html: { class: 's2' }, html: {value: current_user.category} %>
          <%end %>
        </li>
        <% end %>
        <li><%= render 'shared/user_overview', user: current_user, size: size %></li>

        <!-- Notification -->
        <li>
          <%= link_to "#" do %>
            <div class="badge-container">
              <i class="material-icons small">notifications</i>
              <% if @activities_count > 0 %>
                <div class="badge red"><%= @activities_count %></div>
              <% end %>
            </div>
          <% end %>
        </li>

        <!-- Dropdown Trigger -->
        <!-- <li>
          <a class="dropdown-button" href="#!" data-activates="nav-dropdown">
            Profile<i class="material-icons right">arrow_drop_down</i>
          </a>
        </li> -->
      <%# else %>
        <!-- <li>
          <%#= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "waves-effect waves-light btn" %>
        </li> -->
      <% end %>
    </ul>

    <!-- Dropdown list appearing on mobile only -->
    <ul class="side-nav" id="mobile-demo">
      <li><a href="sass.html">Sass</a></li>
      <li><a href="badges.html">Components</a></li>
      <li><a href="collapsible.html">Javascript</a></li>
      <li><a href="mobile.html">Mobile</a></li>
    </ul>
  </div>
  <div id='project-info-wrapper'>
    <%= render 'shared/breadcrumb', breadcrumb_items: breadcrumb_generated_items %>
    <%= render 'projects/timeline' %>
  </div>

</nav>


<!-- Dropdown Structure -->
<!-- <ul id="nav-dropdown" class="dropdown-content">
  <li>
    <%#= link_to "#" do %>
      <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
    <%# end %>
  </li>
  <li>
    <%#= link_to "#" do %>
      <i class="fa fa-home"></i>  <%#= t(".profile", default: "Home") %>
    <%# end %>
  </li>
  <li>
    <%#= link_to destroy_user_session_path, method: :delete do %>
      <i class="fa fa-sign-out"></i>  <%#= t(".sign_out", default: "Log out") %>
    <%# end %>
  </li>
</ul> -->

<%= content_for(:after_js) do %>
  <%= javascript_tag do %>
    $( document ).ready(function(){
       $(".button-collapse").sideNav();
    })
  <% end %>
<% end %>

app/views/shared/_project_infos.html.erb
<div id="small-viewer" class='viewer'>

  <% if @project.picture %>
    <%= cl_image_tag @project.picture.path, width: 635, crop: :fill, class:'responsive-img materialboxed' %>
  <% else %>
    <%= image_tag 'missing_3d_picture.png',  style: 'width:100%;', class:'responsive-img' %>
  <% end %>
</div>
<div class="row">
  <div class="col s12">
    <ul class="tabs small">
      <li class="tab col s3"><a href="#config">Config</a></li>
      <li class="tab col s3"><a class="active" href="#folders">Folders</a></li>
    </ul>
  </div>
  <div id="config" class="col s12 tab-content">
    <%= render 'projects/project_config_summary' %>
  </div>
  <div id="folders" class="col s12">
    <%= render 'projects/repo_tree_form' %>
  </div>
</div>

app/views/shared/_user_badge.html.erb
<span class='center-align btn-floating text bg-<%= user.category %> tooltipped' data-position="right" data-delay="200" data-tooltip="<%= user.name %> - <%= user.category. capitalize %>">
  <%= user.initials %>
</span>

app/views/shared/_user_overview.html.erb
<div class="user-overview <%= size %>">
  <!-- Dropdown Trigger -->
  <a class='dropdown-button' href='#' data-activates='user_actions' data-beloworigin='true' data-constrainwidth='false'>
    <%= image_tag user.picture, alt:"user_profile_picture", class:"avatar-#{size}" %>
  </a>
  <div class="user-identity <%= size %>">
    <span><strong><%= user.name %></strong></span>
    <span class="position">
      <span><%= user.entity.capitalize %></span>
      <span> - </span>
      <span><%= user.category.capitalize %></span>
        <% if size == 'large' %>
          <hr>
          <span class='after-break-line'><%= link_to 'Edit', edit_user_registration_path %></span> -
          <span class='after-break-line'><%= link_to 'Logout', destroy_user_session_path, method: :delete %></span>
        <% end %>
    </span>
  </div>
</div>
<% if size == 'small' %>
  <!-- Dropdown Structure -->
  <ul id='user_actions' class='dropdown-content'>
    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
    <li class="divider"></li>
    <li><%= link_to 'Delete Account', cancel_user_registration_path %></li>
  </ul>
<% end %>

app/views/shared/_vertical_navbar.html.erb
<nav class='vertical-nav-wrapper'>
  <div class="block">
    <% if request.referer %>
      <%= link_to :back,  'data-position' => "right", 'data-delay' => "200", 'data-tooltip' => "Back", class: 'tooltipped' do %>
        <i class="material-icons">arrow_back</i>
      <% end %>
    <% end %>
    <%= link_to projects_path(list: true),  'data-position' => "right", 'data-delay' => "200", 'data-tooltip' => "All Projects", class: 'tooltipped' do %>
      <i class="material-icons">work</i>
    <% end %>
    <%= link_to projects_path,  'data-position' => "right", 'data-delay' => "200", 'data-tooltip' => "Project Catalog", class: 'tooltipped' do %>
      <i class="material-icons">photo_library</i>
    <% end %>

    <%= link_to new_project_path,  'data-position' => "right", 'data-delay' => "200", 'data-tooltip' => "New Project", class: 'tooltipped' do %>
      <i class="material-icons">create_new_folder</i>
    <% end %>
  </div>
  <div class="block">
    <%= link_to meetings_path,  'data-position' => "right", 'data-delay' => "200", 'data-tooltip' => "Meetings", class: 'tooltipped' do %>
      <i class="material-icons">date_range</i>
    <% end %>
  </div>

  <% if user_signed_in? && current_user.category != 'client' %>
    <div class="block">
      <%= link_to '#',  'data-position' => "right", 'data-delay' => "200", 'data-tooltip' => "Data Consumption (coming soon)", class: 'tooltipped' do %>
        <i class="material-icons">data_usage</i>
      <% end %>
      <%= link_to '#',  'data-position' => "right", 'data-delay' => "200", 'data-tooltip' => "Smart Analytics (coming soon)", class: 'tooltipped' do %>
        <i class="material-icons">trending_up</i>
      <% end %>
    </div>
  <% end %>
</nav>