config/routes.rb
Rails.application.routes.draw do
  get 'project_states/update'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'projects#index'

  resources :projects do
    resource :github_webhooks, only: :create, defaults: { formats: :json }
    resources :topics, only: [:create, :show, :update] do
      resources :comments, shallow: true, only: [:create, :update]
    end
    resources :project_states, only: :update
    resources :orders, only: [:create, :update]
    member do
      get 'file/:sha', to: 'repositories#show'
    end
  end

  resources :order_lines, only: :destroy
  resources :meetings

  require "sidekiq/web"
  mount Sidekiq::Web => '/sidekiq'


  mount Attachinary::Engine => "/attachinary"
  mount ActionCable.server => '/cable'

end

app/models/project.rb
class Project < ApplicationRecord
  include Statesman::Adapters::ActiveRecordQueries
  include PublicActivity::Model
  after_commit { NotificationsBroadcastJob.perform_later({
                  resource_class: self.class.to_s,
                  resource_id: self.id,
                  user_id: User.find_by_github_login(self.github_owner).id, # TO DO: variabilize
                  recipient_ids: self.project_users.pluck(:user_id),
                  action: set_notif_action
                })}

  # TO DO => check Trello for models assoc. & valid. to add
  has_many :project_users, dependent: :destroy
  has_many :users, through: :project_users
  has_many :specs, dependent: :destroy
  has_one :purpose, dependent: :destroy
  has_one :material, dependent: :destroy
  has_one :heat_treatment, dependent: :destroy
  has_one :surface, dependent: :destroy
  has_one :dimension, dependent: :destroy
  has_one :quality_control, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :meetings, dependent: :destroy
  has_many :order_lines, dependent: :destroy
  has_many :orders, through: :order_lines, dependent: :destroy
  has_many :transitions, class_name: "ProjectTransition", autosave: false, dependent: :destroy
  has_attachment :picture



  # validates :state, :cycle, presence: true
  validates :title, :client, :measurement_unit, presence: true
  validates :length, :width, :height, :min_wall_thickness, :github_owner,
            :min_hole_diameter, :max_pipe_diameter, presence: true

  validates :length, :width, :numericality => { greater_than: 0, less_than_or_equal_to: BigDecimal.new(250)} # TO DO => if not only mm => convertor
  validates :height, :numericality => { greater_than: 0, less_than_or_equal_to: BigDecimal.new(300)} # TO DO => if not only mm => convertor
  validates :min_wall_thickness, :numericality => { greater_than_or_equal_to: BigDecimal.new(0.2, 3)} # TO DO => if not only mm => convertor
  validates :min_hole_diameter, :numericality => { greater_than_or_equal_to: BigDecimal.new(0.3, 3)} # TO DO => if not only mm => convertor
  validates :max_pipe_diameter, :numericality => { greater_than: 0, less_than: BigDecimal.new(0.8, 3)} # TO DO => if not only mm => convertor
  validates :impossible_details, :trapped_volumes, inclusion: {in: [false], allow_nil: false}


  validates :thales_id, presence: true, uniqueness: true
  validates :repo_id, presence: true, uniqueness: true, on: :update
  validate :minimal_specs_presence

  accepts_nested_attributes_for :specs, :purpose, :material, :heat_treatment,
                                :surface, :dimension, :quality_control,
                                reject_if: :all_blank, allow_destroy: true

  scope :in_phasis, -> (filter) {in_state(ProjectStateMachine.send("#{filter}")).distinct}

  include Project::ExternalInput

  def minimal_specs_presence
    check_spec_standards # to do
    true
  end

  def clients
    users.where(category: 'client')
  end

  def productors
    users.where(category: 'productor')
  end

  def method_officors
    users.where(category: 'method officors')
  end

  def check_spec_standards
    Spec::TYPE.each do | type |
      spec = self.send(type.underscore)
      spec.standard = spec.check_if_standard if spec
    end
  end

  def repo_name
    "#{thales_id}-#{title.gsub(' ','-')}"
  end

  def repo_uri
    "#{github_owner}/#{repo_name}"
  end

  def self.find_from_repo_name(repo_name)
    title = repo_name.gsub(/T3DM-\d{6}-/,'')
    find_by_title(title)
  end

  # STATE MACHINE METHODS
  def state_machine
    @state_machine ||= ProjectStateMachine.new(self, transition_class: ProjectTransition,
                                                     association_name: :transitions)
  end

  def self.transition_name
    :transitions
  end

  def self.transition_class
    ProjectTransition
  end
  private_class_method :transition_class

  def self.initial_state
    :adapt_and_finalize
  end

  def self.last_state
    :done
  end

  def last_order
    orders.last
  end

  def duration
    ((transitions.where(to_state: 'done').limit(1).first.created_at - created_at) / 3600 / 24).ceil
  end

  def set_notif_action
    if transaction_include_any_action?([:create])
      return 'create'
    elsif transaction_include_any_action?([:destroy])
      return 'destroy'
    else
      return 'update'
    end
  end
end

app/models/project/external_input.rb
class Project < ApplicationRecord
  module ExternalInput

    def self.next_thales_id
      # This will need to be plugged to ERP
      self.parent.last ? next_id = (self.parent.last.id + 1).to_s : next_id = '1'
      base = 'T3DM-'
      while next_id.size < 6
        next_id = '0' + next_id
      end
      return (base + next_id).gsub(' ','-')
    end

    def set_default_dimensions
      # TO DO =>  replace with set dimensions when stl upload
      self.length = BigDecimal.new(250)
      self.width = BigDecimal.new(250)
      self.height = BigDecimal.new(300)
      self.measurement_unit = 'mm'
      self.min_wall_thickness = BigDecimal.new(0.2, 3)
      self.min_hole_diameter = BigDecimal.new(0.3, 3)
      self.max_pipe_diameter = BigDecimal.new(0.7, 3)
      self.impossible_details = false
      self.trapped_volumes = false
      return self
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:edit, :update]
  before_action :project_update_params, only: :update
  def index
    if params[:filters]
      # @projects = current_user.projects.in_phasis(params[:filters])
      @projects = policy_scope(Project).in_phasis(params[:filters])
    else
      # @projects = current_user.projects
      @projects = policy_scope(Project)
    end
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def show
    @project = Project.includes(:topics).find(params[:id])
    authorize @project
    mark_notif_as_seen
    @state_machine = @project.state_machine
    @topics = @project.topics
    # when dealing with states & branch
    # @repo_tree = RepoManager.new(current_user.id, @project.id).retrieve_repo_architecture(@project.state_machine.current_base_branch)
    @repo_tree = RepoManager.new(current_user.id, @project.id).retrieve_repo_architecture("master")
    @topic_hashes = TopicManager.new(current_user.id, @project.id).get_project_topics(@topics)

    if !["adapt_and_finalize", "design_analisys"].include?(@state_machine.current_state)
      @order = @project.last_order || Order.new
    end
  end

  def new
    @project = Project.new
    authorize @project
    build_spec_fields
  end

  def create
    @project = Project.new(project_params)
    authorize @project
    # @project.users.push(current_user)
    # TEMPORARY
    temporary_affect_all_users
    @project.client = current_user.entity
    @project.github_owner = current_user.github_login
    @project.set_default_dimensions # TO DO => rework with stl upload
    @project.thales_id = Project::ExternalInput.next_thales_id
    @project.cycle = 'co-engineering'
    if @project.save
      manage_file_upload
      RepoManager.new(current_user.id, @project, {file_path: @file_path, file_name: @file_name}).generate_full_repo
      # TO DO webhook
      redirect_to project_path(@project)
    else
      build_spec_fields
      render :new
    end
  end

  def edit
  end

  def update
    @project = Project.find(params[:id])
    authorize @project
    # TO DO manage permitted params
    # Make a repository controller
    if params[:upload] == 'true'
      manage_file_upload
      # For the moment no new branch
      RepoManager.new(current_user.id, @project, {file_path: @file_path, file_name: @file_name}).upload_file("master", @dir_path, handle_pull_request)
      @repo_tree = RepoManager.new(current_user.id, @project.id).retrieve_repo_architecture("master")
    else
      @project.update(project_params)
    end
    @project.state_machine.next if params[:next] == 'true'
    @project.state_machine.next if params[:previous] == 'true'
    respond_to do |format|
      format.html {redirect_to project_path(@project)}
      format.js {}
    end
  end

  private

   def project_params
    spec_attr = [:id, :title, :description, :_destroy]
    project_params = params.require(:project).permit( :title, :client_project_id, :part_functionality, :notes, :file,
                                     :picture, purpose_attributes: spec_attr, material_attributes: spec_attr,
                                     heat_treatment_attributes: spec_attr, surface_attributes: spec_attr,
                                     dimension_attributes: spec_attr, quality_control_attributes: spec_attr
                                    )
    @file = params[:project][:file]
    project_params.delete(:file)
    return project_params
  end

  def project_update_params
    # #BOURIN +> à investiguer remotipart
    params.permit(:repo, :project, :next, :upload, :previous, :utf8, :_method, :commit, :remotipart_submitted, :authenticity_token, :'X-Requested-With', :'X-Http-Accept', :id)
    if params[:sha]
      params.permit(:sha, :upload, :pull_request, :repo)
      params[:sha].each do |k, v|
        params[:sha].delete(k) if v[:path] == ""
      end
    else
      params.require(:project).permit(:file, :path)
    end
  end

  def find_project
    @project = Project.find(params[:id])
    authorize @project
  end

  def manage_file_upload
    if params[:sha]
      sha_key = params[:sha].keys[0]
      @file = params[:sha][sha_key][:file]
      @dir_path = params[:sha][sha_key][:path]
    else
      @file = params[:project][:file]
      @dir_path = params[:project][:path]
    end
    if @file
      @file_path = @file.tempfile.path
      @file_name = @file.original_filename
    else
      @file_path = nil
      @file_name = nil
    end
  end

  def handle_pull_request
    options = {}
    if params[:pull_request] == 'true'
      options[:new_branch] = "#{@file_name}-#{current_user.name}-#{Time.now.to_i}".gsub(' ','_')
      options[:pr] = true
      options[:pr_title] = params[:repo][:title]
      options[:pr_body] = params[:repo][:content]
    end
    return options
  end

  def build_spec_fields
    # TO DO insert value if params
    @specs = {}
    Spec::TYPE.each do | type |
      type_key = type.underscore.to_sym
      type_attr_key = "#{type.downcase}_attributes"
      if params[:project] && params[:project][type_attr_key]
        value = params[:project][type_attr_key].to_unsafe_h
      else
        value = {}
      end
      @specs[type_key] = instance_variable_set('@' + type.underscore, @project.send('build_' + type.underscore, value))
    end
    return @specs
  end

  def temporary_affect_all_users
    User.all.each {|u| @project.project_users.build(user_id: u.id)}
  end

  def mark_notif_as_seen
    PublicActivity::Activity.where(recipient: current_user, seen: false, trackable_type: 'Project', trackable_id: @project.id).update_all(seen: true)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def breadcrumb_generated_items
    breadcrumb = {}
    if project_breadcrumb_conditions
      breadcrumb[:cycle] = @project.cycle.capitalize
      breadcrumb[:state] = @project.state_machine.current_state.gsub('_', ' ').capitalize
    else
    end
    return breadcrumb
  end

  # def nested_trees(repo)
  #   repo.map do |data, sub_data|
  #     render(partial: "projects/repo_tree", locals: { data: data, subdata: sub_data }) + content_tag(:ul, nested_trees(sub_data), :class => "nested_tree")
  #   end.join.html_safe
  # end

  def nested_trees(repo)
    repo.map do |data, sub_data|
      render layout:"projects/repo_tree", locals: { data: data } do
        content_tag(:ul, nested_trees(sub_data)) if sub_data != {}
      end
    end.join.html_safe
  end

  def truncate_project(title)
    title.size > 23 ? "#{title.first(20)}..." : title
  end

  def project_user_activities(project)
    PublicActivity::Activity.where(recipient: current_user, seen: false, trackable_type: 'Project', trackable_id: project.id).count
  end

  def progress_days(project)
    days = {}
    project.transitions.order(created_at: :asc).reduce(@project.created_at) do | memo, transition |
      day = (transition.created_at - memo) / 3600 / 24
      days[transition.to_state] ? days[transition.to_state] += day : days[transition.to_state] = day
      memo = transition.created_at
    end
    cumulated_days = {"pending" => 0}
    sum = 0
    ProjectStateMachine::STATES.each do | state |
      sum += days[state.to_s].to_f
      cumulated_days[state.to_s] = sum.round(2)

    end
    return cumulated_days
  end

  private
  def project_breadcrumb_conditions
    if %w(projects comments topics).include?(params[:controller])
      %w(show edit).include?(params[:action])
    elsif params[:controller] == 'project_states'
      params[:action] == 'update'
    end
  end

  def format_value(entry, value)
    value ||= 'n/a'
    if entry.nil?
      return value
    else
      return "#{entry.capitalize}: #{value}"
    end
  end
end

app/views/projects/_data_analytics.html.erb
<h4>Execution Key Metrics</h4>
<div class="row">
  <div class="col s3">
    <div class="card-panel bg-turquoise center-align">
      <span class="white-text">
        <span class="data-figure"><%= @project.duration %> </span>
        <span class="data-text">days</span>
      </span>
    </div>
  </div>
  <div class="col s3">
    <div class="card-panel bg-turquoise center-align">
      <span class="white-text">
        <span class="data-figure"><%= Comment.where(topic_id:@project.topics).count + Meeting.where(project_id: @project.id).count %></span>
        <span class="data-text">talks</span>
      </span>
    </div>
  </div>
  <div class="col s3">
    <div class="card-panel bg-turquoise center-align">
      <span class="white-text">
        <span class="data-figure"><%= generate_random_number(1, 10).to_i %></span>
        <span class="data-text">quotations</span>
      </span>
    </div>
  </div>
  <div class="col s3">
    <div class="card-panel bg-turquoise center-align">
      <span class="white-text">
        <span class="data-figure"><%= @project.project_users.count %></span>
        <span class="data-text">collaborators</span>
      </span>
    </div>
  </div>
</div>
<h6>Project completion timeline (days)</h6>
<canvas id="completion-timeline"></canvas>

<h4>Production Key Metrics</h4>
<div class="row">
  <div class="col s3">
    <div class="card-panel bg-turquoise center-align">
      <span class="white-text">
        <span class="data-figure"><%= generate_random_number(1, 10).round(1) %></span>
        <span class="data-text">kg <%= @project.material.title %></span>
      </span>
    </div>
  </div>
  <div class="col s3">
    <div class="card-panel bg-turquoise center-align">
      <span class="white-text">
        <span class="data-figure"><%= number_to_percentage(generate_random_number(0, 1), precision: 1) %></span>
        <span class="data-text">default</span>
      </span>
    </div>
  </div>
  <div class="col s3">
    <div class="card-panel bg-turquoise center-align">
      <span class="white-text">
        <span class="data-figure"><%= generate_random_number(1, 10).to_i %></span>
        <span class="data-text">failure</span>
      </span>
    </div>
  </div>
  <div class="col s3">
    <div class="card-panel bg-turquoise center-align">
      <span class="white-text">
        <span class="data-figure"><%= generate_random_number(500, 2000).round(1) %></span>
        <span class="data-text">MW</span>
      </span>
    </div>
  </div>
</div>
<h6>Machine Capacity Usage(%) </h6>
<canvas id="machine-usage"></canvas>



<%= content_for(:after_js) do %>
  <%= javascript_tag do %>
    $( document ).ready(function(){
      Chart.Bar($('#completion-timeline'), {
        data: {
          labels:  <%= progress_days(@project).keys.to_json.html_safe %>,
          datasets: [
            {
              label: "Phasis days",
              backgroundColor: 'rgba(0, 137, 157, 0.3)',
              borderColor: 'rgba(0, 137, 157, 1)',
              borderWidth: 1,
              data: <%= progress_days(@project).values.to_json.html_safe %> ,
            }
          ]
        },
        options: {
          width: '100%',
          height: '200px',
          legend: { display: false }
        }
      });
    });
    Chart.Line($('#machine-usage'), {
      data: {
        labels:  <%= production_days(@project).to_json.html_safe %>,
        datasets: [
          {
            label: "Machine capacity usage",
            fill: true,
            lineTension: 0.1,
            backgroundColor: "rgba(0, 137, 157, 0.3)",
            borderColor: "rgba(0, 137, 157, 1)",
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: "rgba(75,192,192,1)",
            pointBackgroundColor: "#fff",
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: "rgba(75,192,192,1)",
            pointHoverBorderColor: "rgba(220,220,220,1)",
            pointHoverBorderWidth: 2,
            pointRadius: 1,
            pointHitRadius: 10,
            data: <%= random_machine_usage.values.to_json.html_safe %> ,
            spanGaps: false,
          }
        ]
      },
      options: {
        width: '100%',
        height: '200px',
        legend: { display: false },
        scales: {
          yAxes: [{
            ticks: {
              max: 100,
              min: 0,
              stepSize: 10
            }
          }]
        }
      }
    });
  <% end %>
<% end %>

app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %>
  <h4 class="col s12">Project Details</h4>
  <%= f.error_notification %>
  <%= f.input :title, wrapper_html: { class: 's12' } %>
  <%= f.input :client_project_id, wrapper_html: { class: 's12' } %>
  <div class="form-group">
    <label class="control-label" >T3DM project ID:</label>
    <span class='form-control'><%= Project::ExternalInput.next_thales_id %></span>
  </div>
  <%= f.input :part_functionality, wrapper_html: { class: 's12' }  %></br>
  <%= f.input :notes, wrapper_html: { class: 's12' }  %>
  <%= f.input :picture, as: :file, input_html: {class: 'attachinary'} %>
  <h4 class="col s12" id="specs">Specs</h4>
  <% specs.each do |key, spec| %>
    <%= render 'projects/spec_field', f: f, spec_type: key %>
  <% end %>
  <%= f.button :button, class:'btn', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."} %>
<% end %>

app/views/projects/_order_line_fields.html.erb
<tr>
  <td><%= f.input :description, label: false, placeholder: 'Type line description', wrapper_html: { class: 's12' }  %></td>
  <td><%= f.input :unit_price, as: :float, label: false, placeholder: '120', wrapper_html: { class: 's12' }  %></td>
  <td><%= f.input :duration,  placeholder: '5', label: false, wrapper_html: { class: 's12' } %></td>
  <td class='icon-td'>
    <!-- <%# if order_line.id %>
      <%#= link_to order_line_path(order_line), method: :delete, class: 's1', remote: true do %>
        <i class="tiny material-icons">close</i>
      <%# end %>
    <%# else %>
      <%#= link_to '', class: 's1 no_id_delete' do %>
        <i class="tiny material-icons">close</i>
      <%# end %>
    <%# end %> -->
    <%= link_to_remove_association f do %>
      <i class="tiny material-icons">close</i>
    <% end %>
  </td>
</tr>
<%= f.input :project_id,  as: :hidden, input_html: { value: @project.id } %>

app/views/projects/_project_config_summary.html.erb
<h6 class='project-title'><%= @project.title %></h6>
<ul class='sub-list'>
  <li class='project-data'>Client: <%= @project.client %></li>
  <li class='project-data'>Client Ref: <%= @project.client_project_id %></li>
  <li class='project-data'>Thales Ref: <%= @project.thales_id %></li>
  <li class='project-data'>Functionality: <%= @project.part_functionality %></li>
  <li class='project-state'>Due date: <%= @project.due_date %></li>
  <li class='project-state'>State: <%= @state_machine.current_state %></li>
</ul>

<h6 class='project-title'>Dimensions (<%= @project.measurement_unit %>)</h6>
<ul>
  <li class='project-data'>Width: <%= @project.width %></li>
  <li class='project-data'>Length: <%= @project.length %></li>
  <li class='project-data'>Height: <%= @project.height %></li>
  <li class='project-data'>Min thickness: <%= @project.min_wall_thickness %></li>
  <li class='project-data'>Min hole ø: <%= @project.min_wall_thickness %></li>
  <li class='project-data'>Max pipe ø: <%= @project.min_wall_thickness %></li>
</ul>
<h6 class='project-title'>Specs</h6>
<ul>
  <% @project.specs.each do | spec | %>
    <li class='project-data'><%= spec.full_spec_description %></li>
  <% end %>
</ul>

app/views/projects/_project_list.html.erb
<table class="highlight">
  <thead>
    <tr>
      <th data-field="id">Title</th>
      <th data-field="start_date">Creation</th>
      <th data-field="due_date">Due Date</th>
      <th data-field="status">Status</th>
      <th data-field="collabs">Collaborators</th>
      <th data-field="notifications">Notifications</th>

    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td>
          <%= link_to project_path(project), class:'icon-text-link' do %>
            <i class="material-icons small">folder_open</i><span><%= project.title %></span>
          <% end %>
        </td>
        <td><%= formatted_date(project.created_at) %></td>
        <td><%= formatted_date(project.due_date) %></td>
        <td><%= project.state_machine.current_state.gsub('_', ' ').capitalize %></td>
        <td>
          <ul class='tabs row'>
            <% project.users.each do |user| %>
                <li class='col'>
                  <%= render 'shared/user_badge', user: user %>
                </li>
            <% end %>
          </ul>
        </td>
        <td>
          <% if project_user_activities(project) > 0 %>
            <div class="badge-container">
              <i class="material-icons small">notifications</i>
              <div class="badge red"><%= project_user_activities(project) %></div>
            </div>
          <% end %>
        </td> <!-- TO DO : notifs -->

      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/_repo_tree_form.html.erb
<%= simple_form_for :repo, :url => project_path(@project, upload: true), html: {method: :put, class: 'jstree-form'}, remote: true do |f| %>
  <%= hidden_field_tag "pull_request", nil, {class: 'clean-input'} %>
  <div id="jstree">
    <ul><%= nested_trees(@repo_tree) %></ul>
  </div>
  <%= render 'projects/pull_request_modal_form', f: f %>
<% end %>

app/views/projects/_repo_wrapper.html.erb
<ul>
  <li><%= data.name %>
    <ul><%= yield %></ul>
  </li>
</ul>

app/views/projects/_spec_field.html.erb
<%= f.simple_fields_for spec_type do |p| %>
  <div class="aligned-fields">
    <div class="col s6">
      <% if spec_type.class == Symbol %>
        <% label = spec_type %>
        <% collection = "#{spec_type.to_s.classify}::TITLES".constantize %>
      <%else %>
        <% label = spec_type.class %>
        <% collection = "#{spec_type.class}::TITLES".constantize %>
      <% end %>
      <%= p.input :title, collection: collection, label: label.to_s.gsub('_', ' ').capitalize, wrapper_html: { class: 's12' } %>
    </div>
    <div class="col s6"><%= p.input :description, wrapper_html: { class: 's12 small-size' } %></div>
  </div>
<% end %>

app/views/projects/_step_focus.html.erb
<ul class="title-action">
  <li><h4 class='part-title'>Step Focus</h4></li>
  <li>
    <%= render 'project_states/transition_buttons', state_machine: state_machine %>
  </li>
</ul>
<% if state_machine.in_state?(ProjectStateMachine.production) %>
  <%= render "project_states/production_steps", state_machine: state_machine %>
<% else %>
  <%= render "project_states/#{state_machine.current_state}", state_machine: state_machine %>
<% end %>

app/views/projects/_timeline.html.erb
<% if @project && @project.persisted? %>
  <div class="nav-wrapper" id='timeline'>
    <div id='part1' class="accordion <%= @project.cycle == 'co-engineering' ? 'open' : 'closed' %>">
      <h5 class="timeline-title">Co-Engineering</h5>
      <div class="retracted center-align">
        <i class="material-icons large">remove_red_eye</i>
        <h6>Overview</h6>
      </div>
      <div class="expanded">
        <div class="axis">
          <%= render 'project_states/co-engineering_expanded' %>
        </div>
      </div>

    </div>
    <div id='part2' class="accordion <%= @project.cycle == 'production' ? 'open' : 'closed' %>">
      <h5 class="timeline-title">Production</h5>
      <div class="retracted center-align">

        <i class="material-icons large">remove_red_eye</i>
        <h6>Overview</h6>
      </div>
      <div class="expanded">
        <div class="axis">
          <%= render 'project_states/production_expanded' %>
        </div>
      </div>
    </div>

  </div>
<% end %>

app/views/projects/index.html.erb
<!-- Projects nav -->
<div id='projects-by-status'>
  <div class="row">
    <div class="col s8">
      <ul class="tabs">
        <li class="tab">
          <%= link_to 'All Projects', projects_path(list: params[:list]), target:'', class: 'active', remote: true %>
        </li>
        <li class='tab'>
          <%= link_to 'Co-Engineering', projects_path(filters: 'co_engineering', list: params[:list]), target:'', remote: true %>
        </li>
        <li class='tab'>
          <%= link_to 'Production', projects_path(filters: 'production', list: params[:list]), target:'', remote: true %>
        </li>
        <li class='tab'>
          <%= link_to 'Done', projects_path(filters: 'done', list: params[:list]), target:'', remote: true %>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class='main scroll-y'>
  <div class="row">
    <% if @projects.empty? %>
      <p><em>No project yet! <%= link_to 'Create one', new_project_path %> </em></p>
    <% elsif params[:list] %>
      <%= render 'project_list' %>
    <% else %>
      <%= render 'project_store' %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<!-- Project Overview -->
<div class="col s2 full">
  <%= render 'shared/project_infos' %>
</div>

<!-- Step overview -->
<div id='step-focus' class="col s7 full light-vt-borders">
  <%= render 'projects/step_focus', state_machine: @state_machine %>
<!--   <script src="https://embed.github.com/view/3d/maximedelpit/T3DM-000001-Test-co-eng-new/master/3D%20Models/medaille_ambition10__MEDAILLE_AMBITION10.stl"></script>
  <script src="https://embed.github.com/view/3d/skalnik/secret-bear-clip/master/stl/clip.stl"></script> -->

</div>

<!-- Topics overview -->
<div class="col s3 full">
  <ul class="collapsible custom-accordion" data-collapsible="accordion" id='topic-form-accordion'>
    <li>
      <ul class='title-action collapsible-header'>
        <li><h4 class='part-title'>Topics</h4></li>
        <li>
          <a class="btn-icon-large"><i class="material-icons turquoise">add_circle_outline</i></a>
        </li>
      </ul>
      <div class="collapsible-body" id='topic-form'>
        <%= render 'topics/new', topic: Topic.new %>
      </div>
    </li>
  </ul>
  <%#= render 'topics/filters' %>
  <%= render 'topics/index', topics: @topics %>
</div>